name: "Delay"
description: "Allows you to delay your workflow for a set amount of time."
author: "Bigismall"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "clock"
  color: "red"

# Define your inputs here.
inputs:
  seconds:
    description: "Amout of seconds to delay the workflow for"
    required: true
    default: "1"

# Define your outputs here.
outputs:
  time:
    description: "The time is now"

runs:
  using: node20
  main: dist/index.js
